import { useState } from 'react'
import styles from './ReportForm.module.css'
import { useWallet } from '../hooks/useWallet'
import { buildAuthenticatedHeaders, getApiUrl, parseJsonResponse } from '../utils/backendApi'

function formatDate(value) {
  if (!value) return 'Unavailable'
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return 'Unavailable'

  const day = String(date.getDate()).padStart(2, '0')
  const month = String(date.getMonth() + 1).padStart(2, '0')
  const year = date.getFullYear()
  const hours = String(date.getHours()).padStart(2, '0')
  const minutes = String(date.getMinutes()).padStart(2, '0')
  const seconds = String(date.getSeconds()).padStart(2, '0')
  return `${day}/${month}/${year} ${hours}:${minutes}:${seconds}`
}

function formatLabel(value) {
  return String(value || '')
    .toLowerCase()
    .split('_')
    .filter(Boolean)
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join(' ')
}

const ReportForm = ({ onBack }) => {
  const {
    account,
    chainId,
    isCorrectNetwork,
    connect,
    getSigner,
    error: walletError,
    setError: setWalletError
  } = useWallet()

  const [caseId, setCaseId] = useState('')
  const [status, setStatus] = useState('idle')
  const [errorMsg, setErrorMsg] = useState(null)
  const [reportData, setReportData] = useState(null)

  const generateReport = async () => {
    setErrorMsg(null)

    if (!account) {
      setErrorMsg('Wallet not connected. Please connect MetaMask first.')
      return
    }

    if (!isCorrectNetwork) {
      setErrorMsg('Wrong network. Please switch MetaMask to Sepolia.')
      return
    }

    if (!caseId.trim()) {
      setErrorMsg('Please enter a Case ID before generating a report.')
      return
    }

    setStatus('generating')

    try {
      setWalletError?.(null)
      const signer = await getSigner()
      const headers = await buildAuthenticatedHeaders({
        account,
        chainId,
        signer,
        contentType: 'application/json'
      })

      const response = await fetch(getApiUrl(`/reports/${encodeURIComponent(caseId.trim())}`), {
        method: 'POST',
        headers,
        body: JSON.stringify({})
      })

      const payload = await parseJsonResponse(response, 'Failed to generate report.')
      setReportData(payload)
      setStatus('success')
    } catch (error) {
      setErrorMsg(error?.message || 'Failed to generate report.')
      setStatus('idle')
    }
  }

  return (
    <div className={styles.container}>
      <button onClick={onBack} className={styles.backBtn}>← Back to Dashboard</button>

      <h2 className={styles.heading}>Generate Case Report</h2>
      <p className={styles.subtitle}>
        Generate a pinned JSON report from the local custody ledger and the live on-chain registry.
        Multiple investigators can contribute evidence under the same case ID and it will appear here.
      </p>

      <div className={styles.panel}>
        <div className={styles.formRow}>
          <input
            className={styles.input}
            type="text"
            placeholder="Enter Case ID"
            value={caseId}
            onChange={(event) => setCaseId(event.target.value)}
          />
          <button
            className={styles.actionBtn}
            onClick={generateReport}
            disabled={status === 'generating'}
          >
            {status === 'generating' ? 'Generating Report...' : 'Generate Report'}
          </button>
        </div>

        {(walletError || errorMsg) && (
          <div className={styles.messageBox}>
            <div>{errorMsg || walletError}</div>
            {!account && (
              <button className={styles.secondaryBtn} onClick={connect}>
                Connect MetaMask
              </button>
            )}
          </div>
        )}
      </div>

      {reportData && (
        <div className={styles.reportShell}>
          <div className={styles.summaryCard}>
            <div className={styles.summaryHeader}>
              <div className={styles.iconBadge}>
                <svg viewBox="0 0 48 48" aria-hidden="true">
                  <path d="M14 8h16l8 8v24H14z" />
                  <path d="M30 8v10h8" />
                  <path d="M20 24h12M20 30h12M20 36h8" />
                </svg>
              </div>
              <div>
                <h3>Case Report Ready</h3>
                <p>{reportData.caseId}</p>
              </div>
            </div>

            <div className={styles.summaryGrid}>
              <p><strong>Generated At:</strong> {formatDate(reportData.generatedAt)}</p>
              <p><strong>Generated By:</strong> {reportData.generatedBy}</p>
              <p><strong>Contract:</strong> {reportData.contractAddress}</p>
              <p><strong>Network:</strong> {String(reportData.network || '').toUpperCase()}</p>
              <p><strong>Evidence Count:</strong> {reportData.evidenceCount}</p>
              <p><strong>Ledger Entries:</strong> {reportData.ledgerEntryCount}</p>
              <p><strong>Contributors:</strong> {reportData.contributorCount || reportData.contributors?.length || 0}</p>
              <p>
                <strong>Report CID:</strong> {reportData.reportCid}
                {reportData.reportGatewayUrl && (
                  <a
                    className={styles.inlineLink}
                    href={reportData.reportGatewayUrl}
                    target="_blank"
                    rel="noreferrer"
                  >
                    Open
                  </a>
                )}
              </p>
            </div>
          </div>

          <div className={styles.section}>
            <div className={styles.sectionHeader}>
              <h3>Investigators</h3>
              <span>{reportData.contributors?.length || 0} active contributors</span>
            </div>

            <div className={styles.contributorGrid}>
              {(reportData.contributors || []).map((item) => (
                <article key={item.wallet} className={styles.contributorCard}>
                  <p><strong>Wallet:</strong> {item.wallet}</p>
                  <p><strong>Evidence Added:</strong> {item.evidenceCount}</p>
                  <p><strong>Latest Activity:</strong> {formatDate(item.latestActivityAt)}</p>
                  <p><strong>Officer Names:</strong> {item.officerNames?.length ? item.officerNames.join(', ') : 'Unavailable'}</p>
                </article>
              ))}
            </div>
          </div>

          <div className={styles.section}>
            <div className={styles.sectionHeader}>
              <h3>Evidence Summary</h3>
              <span>{reportData.evidence?.length || 0} records</span>
            </div>

            <div className={styles.evidenceGrid}>
              {(reportData.evidence || []).map((item) => (
                <article key={item.fileHash} className={styles.evidenceCard}>
                  <p><strong>File Hash:</strong> {item.fileHash}</p>
                  <p><strong>Officer:</strong> {item.officerName || 'Unavailable'}</p>
                  <p><strong>Investigator:</strong> {item.investigator || 'Unavailable'}</p>
                  <p><strong>Status:</strong> {item.custodyStatusLabel}</p>
                  <p><strong>Registered:</strong> {formatDate(item.registeredAt)}</p>
                  {item.ipfsCid && (
                    <p>
                      <strong>IPFS CID:</strong> {item.ipfsCid}
                      {item.ipfsGatewayUrl && (
                        <a
                          className={styles.inlineLink}
                          href={item.ipfsGatewayUrl}
                          target="_blank"
                          rel="noreferrer"
                        >
                          Open
                        </a>
                      )}
                    </p>
                  )}
                  {item.txHash && <p><strong>TX Hash:</strong> {item.txHash}</p>}
                </article>
              ))}
            </div>
          </div>

          <div className={styles.section}>
            <div className={styles.sectionHeader}>
              <h3>Case Timeline</h3>
              <span>Ledger-backed activity</span>
            </div>

            <div className={styles.timeline}>
              {(reportData.ledgerEntries || []).map((entry) => (
                <div key={entry.id} className={styles.timelineItem}>
                  <div className={styles.timelineMeta}>
                    <span className={styles.timelineType}>{formatLabel(entry.type)}</span>
                    <span>{formatDate(entry.timestamp || entry.createdAt)}</span>
                  </div>
                  <div className={styles.timelineBody}>
                    <p><strong>Investigator:</strong> {entry.investigator || 'Unavailable'}</p>
                    {entry.fileHash && <p><strong>File Hash:</strong> {entry.fileHash}</p>}
                    {entry.txHash && <p><strong>TX Hash:</strong> {entry.txHash}</p>}
                    {entry.reportCid && (
                      <p>
                        <strong>Report CID:</strong> {entry.reportCid}
                        {entry.reportGatewayUrl && (
                          <a
                            className={styles.inlineLink}
                            href={entry.reportGatewayUrl}
                            target="_blank"
                            rel="noreferrer"
                          >
                            Open
                          </a>
                        )}
                      </p>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

export default ReportForm
